struct WiFiNetwork { ... }; 
WiFiNetwork wifiList[] = { ... };
#define WIFI_COUNT ...
#define API_URL ...
#define CHECK_URL ...
#define DOWNLOAD_URL ...
#define MARK_READ_URL ...
#define API_KEY ...
#define DEVICE_ID ...
